# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Gems
gems: [jekyll-paginate]

# Setup
title:            mehsen
tagline:          'personal mehsite'
description:      'A blog for expressing my strong meh stance on various matters.'
url:              https://mehsen.com
baseurl:          /
enforce_ssl:      mehsen.com

author:
  name:           'Mohsen Dastjerdi Zade'
  url:            https://mehsen.com/me/

paginate:         7

# Custom vars
options:
  theme:			theme-base-0c

social:
  github:           https://github.com/mohsend
  twitter:			https://twitter.com/dstjrd
  googleplus:		https://plus.google.com/+mohsendastjerdizade
  email:			mailto:me@mehsen.com
  linkedin:			https://ir.linkedin.com/in/mohsend
  instagram:		https://www.instagram.com/mehsend/
  telegram:			https://telegram.me/mehsend
