# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty
highlighter:      rouge

# Gems
gems: [jekyll-paginate, jekyll-sitemap]

# Setup
title:            mehsen
tagline:          'personal mehsite'
description:      'A blog to express my strong meh stance on various matters.'
url:              https://mehsen.com
baseurl:          ''
enforce_ssl:      mehsen.com

author:
  name:           'Mohsen Dastjerdi Zade'
  url:            https://mehsen.com/me/
  email:

paginate:         7

# Custom vars
options:
  bodyclass:			'theme-base-0c'
  license:        '<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons Attribution License" style="border-width:0; display: inline; margin: 0;" src="/public/cc-by.png" /></a> <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">mehsen</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://mehsen.com" property="cc:attributionName" rel="cc:attributionURL">Mohsen Dastjerdi Zade</a>.'
  image:          '/public/favicon/apple-touch-icon-precomposed.png'

social:
  github:       https://github.com/mohsend/
  twitter:			https://twitter.com/dstjrd/
  googleplus:		https://plus.google.com/+mohsendastjerdizade/
  email:			  mailto:me@mehsen.com
  linkedin:			https://ir.linkedin.com/in/mohsend/
  instagram:		https://www.instagram.com/mehsend/
  telegram:			https://telegram.me/mehsend/
  goodreads:		https://www.goodreads.com/mohsend/
