# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty
highlighter:      rouge

# Gems
gems: [jekyll-paginate]

# Setup
title:            mehsen
tagline:          'personal mehsite'
description:      'A blog to express my strong meh stance on various matters.'
url:              https://mehsen.com
baseurl:          /
enforce_ssl:      mehsen.com

author:
  name:           'Mohsen Dastjerdi Zade'
  url:            https://mehsen.com/me/
  email:

paginate:         7

# Custom vars
options:
  theme:			theme-base-0c
  license:          '<a href="https://creativecommons.org/licenses/by/4.0/" rel="license"><img src="/public/cc-by.png" style="display: inline; margin: 0; width: 80px; height: 15px;" alt="Creative Commons Attribution License" alt="Creative Commons Attribution License"></a>'
  image:			'public/favicon/apple-touch-icon-180x180.png'

social:
  github:           https://github.com/mohsend
  twitter:			https://twitter.com/dstjrd
  googleplus:		https://plus.google.com/+mohsendastjerdizade
  email:			mailto:me@mehsen.com
  linkedin:			https://ir.linkedin.com/in/mohsend
  instagram:		https://www.instagram.com/mehsend/
  telegram:			https://telegram.me/mehsend
